### PR TITLE
allow overriding a few more fields

### PR DESCRIPTION
**Pull request by sherzberg**
just cherrypicks part of the changes from https://github.com/sourcegraph/terraform-provider-site24x7/pull/2

### CODE REVIEW

**Comment by sherzberg** [comment]
@neelance here you go!

**Review by neelance — APPROVED** [review]

**Comment by neelance** [comment]
Thx!

**Comment by neelance** [comment]
@sherzberg Unfortunately I had to revert this change since it was breaking the tests and our own configuration. If you're still interested in seeing this on master (which I would appreciate), then please run the tests via `env TF_ACC=true go test -v ./site24x7/` and figure out a solution that does not break them.

**Comment by nicksnyder** [comment]
For the record, all you need to do is specify both `Computed` and `Optional`.

See https://github.com/sourcegraph/terraform-provider-site24x7/commit/6c7bb171bca6151c047fa120a9e4629ecaaa67a2

**Pull request merged**
